name: Build ISO

on:
  push:
      paths-ignore:
      - '**.md'
  pull_request:
        paths-ignore:
        - '**.md'
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thevakhovske/holoiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Sanity check, if we are on SteamOS environment
        run: |
          cat /etc/os-release          
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso

      - name: Build ISO File
        run: |
          cp mkarchiso-holoiso /usr/bin
          chmod +x /usr/bin/mkarchiso-holoiso
          mkarchiso-holoiso -v .
          find out/
          
      - name: Split file
        run: |
          zip -r -s 1g out/$(ls out).zip out/$(ls out)
          rm out/HoloISO*.iso
          
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "out/*"
          tags: true
          draft: true
          prerelease: true
