name: Build ISO self-hosted

on:
  push:
      paths-ignore:
      - '**.md'
  pull_request:
        paths-ignore:
        - '**.md'
  

jobs:
  build:
    runs-on: self-hosted
    # container:
    #   image: thevakhovske/holoiso:latest
    #   options: --privileged
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      # - name: Sanity check, if we are on SteamOS environment
      #   run: |
      #     cat /etc/os-release          
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso

      - name: Build ISO File
        run: |
          cp mkarchiso-holoiso /usr/bin
          chmod +x /usr/bin/mkarchiso-holoiso

          rm -rf efiboot/loader/entries
          mkdir -p efiboot/loader/entries
          ./gen_entries.sh .
          
          mkarchiso-holoiso -v .
          find out/

      - uses: actions/upload-artifact@v2
        with:
          name: holoiso
          path: out/*.iso
          
      - uses: actions/upload-artifact@v2
        with:
          name: holoiso-misc-data
          path: ./*.pacman
